<?php

/**
 * This is the model base class for the table "tEstadoCivil".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TEstadoCivil".
 *
 * Columns in table "tEstadoCivil" available as properties of the model,
 * followed by relations of table "tEstadoCivil" available as properties of the model.
 *
 * @property string $id_estado_civil
 * @property string $descripcion
 *
 * @property TPersona[] $tPersonas
 */
abstract class BaseTEstadoCivil extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tEstadoCivil';
    }

    public static function representingColumn() {
        return 'descripcion';
    }

    public function rules() {
        return array(
            array('descripcion', 'length', 'max'=>50),
            array('descripcion', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_estado_civil, descripcion', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'tPersonas' => array(self::HAS_MANY, 'TPersona', 'id_estado_civil'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_estado_civil' => Yii::t('app', 'Id Estado Civil'),
                'descripcion' => Yii::t('app', 'Descripcion'),
                'tPersonas' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_estado_civil', $this->id_estado_civil, true);
        $criteria->compare('descripcion', $this->descripcion, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}