<?php

/**
 * This is the model base class for the table "tProveedor".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TProveedor".
 *
 * Columns in table "tProveedor" available as properties of the model,
 * followed by relations of table "tProveedor" available as properties of the model.
 *
 * @property integer $id_proveedor
 * @property string $nombre
 * @property string $ci_ruc
 * @property integer $tel_fij_prov
 * @property integer $tel_mov_prov
 * @property string $direccion
 * @property string $cue_banc_prov
 * @property string $fecha
 * @property integer $id_usuario
 *
 * @property TArticulo[] $tArticulos
 */
abstract class BaseTProveedor extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tProveedor';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('ci_ruc, nombre', 'required'),
            array('tel_fij_prov, tel_mov_prov, id_usuario', 'numerical', 'integerOnly'=>true),
            array('ci_ruc', 'length', 'max'=>13),
            array('nombre', 'length', 'max'=>60),
            array('direccion', 'length', 'max'=>100),
            array('cue_banc_prov', 'length', 'max'=>100),
            array('fecha', 'safe'),
            array('tel_fij_prov, tel_mov_prov, direccion, cue_banc_prov, fecha, id_usuario', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_proveedor, ci_ruc, nombre, tel_fij_prov, tel_mov_prov, direccion, cue_banc_prov, fecha, id_usuario', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'tArticulos' => array(self::HAS_MANY, 'TArticulo', 'id_proveedor'),
            'idUsuario' => array(self::BELONGS_TO, 'Usuario', 'id_usuario'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_proveedor' => Yii::t('app', 'Id de Proveedor'),
            'ci_ruc' => Yii::t('app', 'CI o RUC'),
                'nombre' => Yii::t('app', 'Nombres y apellidos'),
                'tel_fij_prov' => Yii::t('app', 'Teléfono'),
                'tel_mov_prov' => Yii::t('app', 'Celular'),
                'direccion' => Yii::t('app', 'Dirección'),
                'cue_banc_prov' => Yii::t('app', 'Cuenta bancaria'),
                'fecha' => Yii::t('app', 'El: '),
                'id_usuario' => Yii::t('app', 'Modificado por: '),
                'tArticulos' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_proveedor', $this->id_proveedor);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('ci_ruc', $this->ci_ruc, true);
        $criteria->compare('tel_fij_prov', $this->tel_fij_prov);
        $criteria->compare('tel_mov_prov', $this->tel_mov_prov);
        $criteria->compare('direccion', $this->direccion, true);
        $criteria->compare('cue_banc_prov', $this->cue_banc_prov, true);
        $criteria->compare('fecha', $this->fecha, true);
        $criteria->compare('id_usuario', $this->id_usuario);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}