<?php

/**
 * This is the model base class for the table "tEmpresa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TEmpresa".
 *
 * Columns in table "tEmpresa" available as properties of the model,
 * followed by relations of table "tEmpresa" available as properties of the model.
 *
 * @property integer $id_empresa
 * @property string $empresa
 * @property string $ruc
 * @property string $nombre_responsable
 * @property string $cioruc_responsable
 * @property string $direccion
 * @property string $telefono
 * @property string $celular
 * @property string $email
 * @property string $fecha
 * @property integer $id_usuario
 *
 * @property Usuario[] $usuarios
 */
abstract class BaseTEmpresa extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tEmpresa';
    }

    public static function representingColumn() {
        return 'empresa';
    }

    public function rules() {
        return array(
            array('empresa, nombre_responsable, cioruc_responsable', 'required'),
            array('id_usuario', 'numerical', 'integerOnly'=>true),
            array('empresa, ruc, nombre_responsable, cioruc_responsable', 'length', 'max'=>75),
            array('direccion, telefono, celular, email', 'length', 'max'=>200),
            array('fecha', 'safe'),
            array('ruc, direccion, telefono, celular, email, fecha, id_usuario', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_empresa, empresa, ruc, nombre_responsable, cioruc_responsable, direccion, telefono, celular, email, fecha, id_usuario', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'usuarios' => array(self::HAS_MANY, 'Usuario', 'id_empresa'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_empresa' => Yii::t('app', 'Id Empresa'),
                'empresa' => Yii::t('app', 'Empresa'),
                'ruc' => Yii::t('app', 'Ruc'),
                'nombre_responsable' => Yii::t('app', 'Nombre Responsable'),
                'cioruc_responsable' => Yii::t('app', 'Cioruc Responsable'),
                'direccion' => Yii::t('app', 'Direccion'),
                'telefono' => Yii::t('app', 'Telefono'),
                'celular' => Yii::t('app', 'Celular'),
                'email' => Yii::t('app', 'Email'),
                'fecha' => Yii::t('app', 'Fecha'),
                'id_usuario' => Yii::t('app', 'Id Usuario'),
                'usuarios' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_empresa', $this->id_empresa);
        $criteria->compare('empresa', $this->empresa, true);
        $criteria->compare('ruc', $this->ruc, true);
        $criteria->compare('nombre_responsable', $this->nombre_responsable, true);
        $criteria->compare('cioruc_responsable', $this->cioruc_responsable, true);
        $criteria->compare('direccion', $this->direccion, true);
        $criteria->compare('telefono', $this->telefono, true);
        $criteria->compare('celular', $this->celular, true);
        $criteria->compare('email', $this->email, true);
        $criteria->compare('fecha', $this->fecha, true);
        $criteria->compare('id_usuario', $this->id_usuario);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}