<?php

/**
 * This is the model base class for the table "tSexo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TSexo".
 *
 * Columns in table "tSexo" available as properties of the model,
 * followed by relations of table "tSexo" available as properties of the model.
 *
 * @property string $id_sexo
 * @property string $descripcion
 *
 * @property TPersona[] $tPersonas
 */
abstract class BaseTSexo extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tSexo';
    }

    public static function representingColumn() {
        return 'descripcion';
    }

    public function rules() {
        return array(
            array('descripcion', 'length', 'max'=>25),
            array('descripcion', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_sexo, descripcion', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'tPersonas' => array(self::HAS_MANY, 'TPersona', 'id_sexo'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_sexo' => Yii::t('app', 'Id Sexo'),
                'descripcion' => Yii::t('app', 'Descripcion'),
                'tPersonas' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_sexo', $this->id_sexo, true);
        $criteria->compare('descripcion', $this->descripcion, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}