<?php

/**
 * This is the model base class for the table "tContratoGarante".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TContratoGarante".
 *
 * Columns in table "tContratoGarante" available as properties of the model,
 * followed by relations of table "tContratoGarante" available as properties of the model.
 *
 * @property string $id_cont_garante
 * @property string $numero_contrato
 * @property integer $id_garante
 * @property string $tipo
 * @property string $fecha
 * @property integer $id_usuario
 *
 * @property TPersona $idGarante
 * @property TContrato $numeroContrato
 */
abstract class BaseTContratoGarante extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tContratoGarante';
    }

    public static function representingColumn() {
        return 'fecha';
    }

    public function rules() {
        return array(
            array('numero_contrato, id_garante', 'required'),
            array('id_garante, id_usuario', 'numerical', 'integerOnly'=>true),
            array('numero_contrato', 'length', 'max'=>11),
            array('tipo', 'length', 'max'=>25),
            array('tipo, id_usuario', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_cont_garante, numero_contrato, id_garante, tipo, fecha, id_usuario', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'idGarante' => array(self::BELONGS_TO, 'TPersona', 'id_garante'),
            'numeroContrato' => array(self::BELONGS_TO, 'TContrato', 'numero_contrato'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_cont_garante' => Yii::t('app', 'Identificador'),
                'numero_contrato' => Yii::t('app', 'Numero Contrato'),
                'id_garante' => Yii::t('app', 'Garante'),
                'tipo' => Yii::t('app', 'Tipo'),
                'fecha' => Yii::t('app', 'Ultima modificación'),
                'id_usuario' => Yii::t('app', 'Modificado por'),
                'idGarante' => null,
                'numeroContrato' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_cont_garante', $this->id_cont_garante, true);
        $criteria->compare('numero_contrato', $this->numero_contrato);
        $criteria->compare('id_garante', $this->id_garante);
        $criteria->compare('tipo', $this->tipo, true);
        $criteria->compare('fecha', $this->fecha, true);
        $criteria->compare('id_usuario', $this->id_usuario);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}