<?php

/**
 * This is the model base class for the table "tFormaPago".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TFormaPago".
 *
 * Columns in table "tFormaPago" available as properties of the model,
 * followed by relations of table "tFormaPago" available as properties of the model.
 *
 * @property integer $id_formapago
 * @property string $forma_pago
 * @property string $id_usuario
 * @property string $fecha
 *
 * @property TContrato[] $tContratos
 */
abstract class BaseTFormaPago extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tFormaPago';
    }

    public static function representingColumn() {
        return 'forma_pago';
    }

    public function rules() {
        return array(
            array('forma_pago', 'required'),
            array('forma_pago, id_usuario', 'length', 'max'=>45),
            array('fecha', 'safe'),
            array('id_usuario, fecha', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_formapago, forma_pago, id_usuario, fecha', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'tContratos' => array(self::HAS_MANY, 'TContrato', 'id_formaPago'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_formapago' => Yii::t('app', 'Id Formapago'),
                'forma_pago' => Yii::t('app', 'Forma Pago'),
                'id_usuario' => Yii::t('app', 'Id Usuario'),
                'fecha' => Yii::t('app', 'Fecha'),
                'tContratos' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_formapago', $this->id_formapago);
        $criteria->compare('forma_pago', $this->forma_pago, true);
        $criteria->compare('id_usuario', $this->id_usuario, true);
        $criteria->compare('fecha', $this->fecha, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}