<?php

/**
 * This is the model base class for the table "tPersona".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TPersona".
 *
 * Columns in table "tPersona" available as properties of the model,
 * followed by relations of table "tPersona" available as properties of the model.
 *
 * @property integer $ci
 * @property string $nombre
 * @property string $id_sexo
 * @property string $id_estado_civil
 * @property string $direccion
 * @property string $referencia
 * @property string $telefono
 * @property integer $celular
 * @property string $trabajo
 * @property string $cargo
 * @property string $tiempo
 * @property string $dir_trabajo
 * @property integer $tel_trabajo
 * @property integer $cel_trabajo
 * @property integer $sueldo
 * @property integer $ci_cony
 * @property string $nombre_cony
 * @property string $trabajo_cony
 * @property string $cargo_cony
 * @property string $tiempo_cony
 * @property string $dir_trabajo_cony
 * @property integer $tel_trabajo_cony
 * @property integer $cel_trabajo_cony
 * @property integer $sueldo_cony
 * @property integer $id_casa
 * @property string $tiempo_arriendo
 * @property string $ci_digital
 * @property string $fecha
 * @property integer $id_usuario
 *
 * @property TContrato[] $tContratos
 * @property TContratoGarante[] $tContratoGarantes
 * @property TEstadoCivil $idEstadoCivil
 * @property TSexo $idSexo
 */
abstract class BaseTPersona extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tPersona';
    }

    public static function representingColumn() {
        return 'nombre';
    }
	public static function representingColumnCI()
    {
	return 'ci';
    }

    public function rules() { 
        return array(
            array('ci, nombre, direccion, id_casa', 'required'),
            array('ci', 'unique'),
            array('sueldo, sueldo_cony, id_casa, id_usuario', 'numerical', 'integerOnly'=>true),
            array('tel_trabajo_cony, cel_trabajo_cony, celular, tel_trabajo, cel_trabajo, telefono, nombre, direccion, nombre_cony', 'length', 'max'=>60),
            array('id_sexo, id_estado_civil', 'length', 'max'=>11),
            array('referencia, trabajo, cargo, dir_trabajo, trabajo_cony, cargo_cony, dir_trabajo_cony', 'length', 'max'=>150),
            array('tiempo, tiempo_cony', 'length', 'max'=>50),
            array('tiempo_arriendo', 'length', 'max'=>25),
            array('ci_digital', 'length', 'max'=>100),
            array('fecha', 'safe'),
            array('id_sexo, id_estado_civil, telefono, celular, trabajo, cargo, tiempo, dir_trabajo, tel_trabajo, cel_trabajo, sueldo, ci_cony, nombre_cony, trabajo_cony, cargo_cony, tiempo_cony, dir_trabajo_cony, tel_trabajo_cony, cel_trabajo_cony, sueldo_cony, id_casa, tiempo_arriendo, ci_digital, fecha, id_usuario', 'default', 'setOnEmpty' => true, 'value' => null),
            array('ci, nombre, id_sexo, id_estado_civil, direccion, referencia, telefono, celular, trabajo, cargo, tiempo, dir_trabajo, tel_trabajo, cel_trabajo, sueldo, ci_cony, nombre_cony, trabajo_cony, cargo_cony, tiempo_cony, dir_trabajo_cony, tel_trabajo_cony, cel_trabajo_cony, sueldo_cony, id_casa, tiempo_arriendo, ci_digital, fecha, id_usuario', 'safe', 'on'=>'search'),
        );
    } 

    public function relations() {
        return array(
            'tContratos' => array(self::HAS_MANY, 'TContrato', 'id_deudor'),
            'tContratoGarantes' => array(self::HAS_MANY, 'TContratoGarante', 'id_garante'),
            'idEstadoCivil' => array(self::BELONGS_TO, 'TEstadoCivil', 'id_estado_civil'),
            'idSexo' => array(self::BELONGS_TO, 'TSexo', 'id_sexo'),
            'idCasa' => array(self::BELONGS_TO, 'TCasa', 'id_casa'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ci' => Yii::t('app', 'CI'),
                'nombre' => Yii::t('app', 'Apellidos y Nombres'),
                'id_sexo' => Yii::t('app', 'Género'),
                'id_estado_civil' => Yii::t('app', 'Estado Civil'),
                'direccion' => Yii::t('app', 'Dirección del domicilio'),
                'referencia' => Yii::t('app', 'Referencia o detalles del domicilio'),
                'telefono' => Yii::t('app', 'Teléfono'),
                'celular' => Yii::t('app', 'Celular'),
                'trabajo' => Yii::t('app', 'Lugar del trabajo'),
                'cargo' => Yii::t('app', 'Cargo'),
                'tiempo' => Yii::t('app', 'Tiempo'),
                'dir_trabajo' => Yii::t('app', 'Dirección del trabajo'),
                'tel_trabajo' => Yii::t('app', 'Teléfono del trabajo'),
                'cel_trabajo' => Yii::t('app', 'Celular del trabajo'),
                'sueldo' => Yii::t('app', 'Sueldo'),
                'ci_cony' => Yii::t('app', 'CI'),
                'nombre_cony' => Yii::t('app', 'Apellidos y Nombres'),
                'trabajo_cony' => Yii::t('app', 'Trabajo'),
                'cargo_cony' => Yii::t('app', 'Cargo'),
                'tiempo_cony' => Yii::t('app', 'Tiempo'),
                'dir_trabajo_cony' => Yii::t('app', 'Dirección del trabajo'),
                'tel_trabajo_cony' => Yii::t('app', 'Teléfono del trabajo'),
                'cel_trabajo_cony' => Yii::t('app', 'Celular del trabajo'),
                'sueldo_cony' => Yii::t('app', 'Sueldo'),
                'id_casa' => Yii::t('app', 'Su casa es'),
                'tiempo_arriendo' => Yii::t('app', 'Tiempo de arriendo (solo en caso de ser arrendada)'),
                'ci_digital' => Yii::t('app', 'CI en digital'),
                'fecha' => Yii::t('app', 'El: '),
                'id_usuario' => Yii::t('app', 'Modificado por: '),
                'tContratos' => null,
                'tContratoGarantes' => null,
                'idEstadoCivil' => null,
                'idSexo' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ci', $this->ci);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('id_sexo', $this->id_sexo);
        $criteria->compare('id_estado_civil', $this->id_estado_civil);
        $criteria->compare('direccion', $this->direccion, true);
        $criteria->compare('referencia', $this->referencia, true);
        $criteria->compare('telefono', $this->telefono);
        $criteria->compare('celular', $this->celular);
        $criteria->compare('trabajo', $this->trabajo, true);
        $criteria->compare('cargo', $this->cargo, true);
        $criteria->compare('tiempo', $this->tiempo, true);
        $criteria->compare('dir_trabajo', $this->dir_trabajo, true);
        $criteria->compare('tel_trabajo', $this->tel_trabajo);
        $criteria->compare('cel_trabajo', $this->cel_trabajo);
        $criteria->compare('sueldo', $this->sueldo);
        $criteria->compare('ci_cony', $this->ci_cony);
        $criteria->compare('nombre_cony', $this->nombre_cony, true);
        $criteria->compare('trabajo_cony', $this->trabajo_cony, true);
        $criteria->compare('cargo_cony', $this->cargo_cony, true);
        $criteria->compare('tiempo_cony', $this->tiempo_cony, true);
        $criteria->compare('dir_trabajo_cony', $this->dir_trabajo_cony, true);
        $criteria->compare('tel_trabajo_cony', $this->tel_trabajo_cony);
        $criteria->compare('cel_trabajo_cony', $this->cel_trabajo_cony);
        $criteria->compare('sueldo_cony', $this->sueldo_cony);
        $criteria->compare('id_casa', $this->id_casa);
        $criteria->compare('tiempo_arriendo', $this->tiempo_arriendo, true);
        $criteria->compare('ci_digital', $this->ci_digital, true);
        $criteria->compare('fecha', $this->fecha, true);
        $criteria->compare('id_usuario', $this->id_usuario);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}
